sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t techxorcist/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true techxorcist/react-test npm test

after_success:
  - docker build -t techxorcist/multi-client -f ./client
  - docker build -t techxorcist/multi-nginx -f ./nginx
  - docker build -t techxorcist/multi-server -f ./server
  - docker build -t techxorcist/multi-worker -f ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push the images to dockerhub
  - docker push techxorcist/multi-client
  - docker push techxorcist/multi-nginx
  - docker push techxorcist/multi-server
  - docker push techxorcist/multi-worker
